data:
  input_path: "data/TinyStoriesV2-GPT4-train.txt"
  vocab_path: "data/vocab/tinystories_sample_5M_vocab.pkl"
  merges_path: "data/vocab/tinystories_sample_5M_merges.pkl"
training:
  vocab_size: 12800
  special_tokens: ["<|endoftext|>"]
